export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  CHAT: "/chat",
  BOTS: "/bots",
  BOT_DETAIL: "/bots/:id",
  KNOWLEDGE: "/knowledge",
  KNOWLEDGE_DETAIL: "/knowledge/:id",
  FEEDBACK: "/feedback",
  FEEDBACK_BROWSER: "/feedback/browser",
  FEEDBACK_CONVERSATION: "/feedback/:conversationId",
  SETTINGS: "/settings",
  SETTINGS_PROVIDERS: "/settings/providers",
  ADMIN_LOGS: "/admin/logs",
  ADMIN_KNOWLEDGE_BASES: "/admin/knowledge-bases",
  ADMIN_KB_DETAIL: "/admin/knowledge-bases/:id",
  ADMIN_BOTS: "/admin/bots",
  ADMIN_BOT_DETAIL: "/admin/bots/:id",
  ADMIN_USERS: "/admin/users",
  ADMIN_OBSERVABILITY: "/admin/observability",
  ADMIN_TOKEN_USAGE: "/admin/token-usage",
  ADMIN_MCP_REGISTRY: "/admin/mcp-registry",
  ADMIN_TENANTS: "/admin/tenants",
  ADMIN_PROMPTS: "/admin/prompts",
  ADMIN_DIAGNOSTIC_RULES: "/admin/diagnostic-rules",
  ADMIN_RATE_LIMITS: "/admin/rate-limits",
} as const;
